# Generated by Django 5.2 on 2025-04-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_account_credit_limit_account_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='usage',
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.account')),
                ('current_usage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('finances.account',),
        ),
        migrations.CreateModel(
            name='DebitAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.account')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            bases=('finances.account',),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.account')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('finances.account',),
        ),
    ]
