# Generated by Django 5.2 on 2025-04-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_account_credit_limit_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-tag', max_length=50),
        ),
    ]
