# Generated by Django 5.2 on 2025-04-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_account_credit_limit_remove_account_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.account'),
        ),
        migrations.AddField(
            model_name='budget',
            name='duration',
            field=models.CharField(choices=[('1 week', '1 Week'), ('1 month', '1 Month')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('category', 'user', 'month', 'account')},
        ),
    ]
