# Generated by Django 5.2 on 2025-04-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_subcategory_transaction_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=7),
        ),
    ]
