# Generated by Django 5.2 on 2025-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_category_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
