# Generated by Django 5.2 on 2025-04-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_debt'),
        ('finances', '0007_category_type'),
    ]

    operations = [
    ]
