# Generated by Django 5.2 on 2025-04-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_merge_0005_debt_0007_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='account',
        ),
    ]
