# Generated by Django 5.2 on 2025-04-29 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Philippine Peso (₱)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('KRW', 'Korean Won (₩)')], default='PHP', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_photos/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.account'),
        ),
    ]
