# Generated by Django 5.2 on 2025-04-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_category_options_category_order'),
        ('finances', '0009_remove_debt_account'),
    ]

    operations = [
    ]
