# Generated by Django 5.2 on 2025-04-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_alter_transaction_options_transaction_currency_and_more'),
        ('finances', '0010_merge_20250430_0303'),
    ]

    operations = [
    ]
