# Generated by Django 5.2 on 2025-04-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_merge_20250430_1315'),
        ('finances', '0012_scheduledtransaction'),
    ]

    operations = [
    ]
