# Generated by Django 5.2 on 2025-04-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_merge_20250430_1600'),
    ]

    operations = [
    ]
