# Generated by Django 5.2 on 2025-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_merge_20250430_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-tag', max_length=50),
        ),
    ]
