# Generated by Django 5.2 on 2025-04-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_auto_20250430_1603'),
        ('finances', '0014_remove_transaction_account_alter_category_icon'),
    ]

    operations = [
    ]
