# Generated by Django 5.2 on 2025-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_remove_transaction_account_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransaction',
            name='last_occurrence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='occurrences_remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
