# Generated by Django 5.2 on 2025-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_scheduledtransaction_last_occurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='minimum_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
