# Generated by Django 5.2 on 2025-05-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_alter_budget_unique_together_budget_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
    ]
