# Generated by Django 5.2 on 2025-05-01 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.IntegerField(default=2)),
                ('visible_elements', models.TextField(default='["accounts", "budgets", "chart-balance", "chart-last-7-days"]')),
                ('hidden_elements', models.TextField(default='["credit-cards", "debts-credits", "transactions", "scheduled-transactions", "balance-currency", "cash-flow"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
