# Generated by Django 5.2 on 2025-05-02 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_dashboardpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('category', 'subcategory', 'user', 'start_date', 'account')},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'category'], name='finances_bu_user_id_a467df_idx'),
        ),
    ]
