# Generated by Django 5.2 on 2025-05-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_alter_budget_unique_together_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtransaction',
            options={'ordering': ['date_scheduled']},
        ),
        migrations.RemoveField(
            model_name='scheduledtransaction',
            name='occurrences_remaining',
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='next_occurrence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='date_scheduled',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='repeat_type',
            field=models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=7),
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='repeats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
