# Generated by Django 5.2 on 2025-05-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_alter_scheduledtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='occurrence_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_transactions', to='finances.scheduledtransaction'),
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
