# Generated by Django 5.2 on 2025-05-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0022_scheduledtransaction_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='date_scheduled',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='last_occurrence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='next_occurrence',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
